### ISSUE TITLE
how to use this docker？

### ISSUE THREAD

**Issue by MadornC** [btmnk/vrising-docker#1]
i wanna move my server into linux system,please tell me how to use this docker

**Comment by btmnk** [comment]
Well you kinda just run `docker compose up` and it should work ootb.
Make sure to open the ports used in the settings.
(You might have to connect directly via IP, I couldn't figure out yet why it doesn't show up in the list)

You can also remove the two settings files in the settings directory, the server will generate the defaults into the settings directory if they're not present. I think I accidentally pushed some changes to the settings files that are not defaults.

If I find time next week I'll add a Readme to the project on how to use it with some more details.

**Comment by btmnk** [comment]
I added a readme and removed the changed settings. Let me know if you have any issues.
